### ISSUE TITLE
Limited support CXA60

### ISSUE THREAD

**Issue by fritsypeij** [andrew-bolin/pi_hifi_ctrl#3]
Hi Andrew,

Thanks for putting this online! I tried your code on my CXA60 and only seems to support the vol+ / - and mute on / off. I added all commands corresponding to the ones [supplied by Cambridge Audio](https://techsupport.cambridgeaudio.com/hc/en-us/articles/202512152-CXA60-CXA80-IR-Remote-Control-Codes):

```
cmd = {
        'a1': 100,
        'a2': 101,
        'a3': 102,
        'a4': 103,
        'd1': 105,
        'd2': 106,
        'd3': 107,
        'mp3': 108,
        'bt': 115,
        'power': 12,
        'poweron': 14,
        'poweroff': 15,
        'mute': 13,
        'muteon': 50,   # works
        'muteoff': 51,  # works
        'vol+': 16,     # works
        'vol-': 17,     # works
        'bright': 72,   
        'bright0': 71,
        'bright1': 19,
        'bright2': 18,
        'speaker': 20,
        'speakera': 35,
        'speakerb': 39,
        'speakerab': 30,
        'direct': 78,
        'triggera': 82,
        'triggerb': 83,
        'triggerc': 84,
        'source-': 126,
        'source+': 99
        }
```

Do you think Cambridge Audio limited the commands via Control Bus?

**Comment by andrew-bolin** [comment]
Hi, good to hear someone else is using it!

I don't think they limited the commands. I think they would take the easy
way out and just wire the control bus straight into the same place as the
IR.

My implementation of the RC-5 message format does not allow codes greater
than 63. (Just looking at wikipedia now, there is a "field" bit which I
never noticed/implemented)
So that might explain some of them, but the power codes should still work!

Try this. Inside the build_rc5 function, replace "RC5_START = 0b110" with:
        if (cmd<64):
                field = 1
        else:
                field = 0
        RC5_START = 0b100 + (0b010 * field)

(I'll try to update it on github soon)

There's also a "toggle bit" in the RC5 protocol I never implemented,
because I didn't need it. If your volume controls work reliably then we can
probably assume that's not the problem though.

It could be worth trying other codes, 64 and 68 would be good candidates to
test for power on (from
https://techsupport.cambridgeaudio.com/hc/en-us/articles/200551872-340R-540R-IR-Codes
)

Oh, I should check - are you using ca_amp_ctrl.py from command line, or the
HDMI scraper cec_stream.py ?
The HDMI script is pretty bad, and only does power and volume (mute is
quirky)... but it does work for me.

**Comment by fritsypeij** [comment]
I'm using `ca_amp_ctrl.py`.
I checked all commands, only volume and mute seemed to work (power toggle, on and off didn't). I will try again with the extra bit tonight. 

Edit: Still no power (or other functions for that matter)

The more I'm trying, the more I'm starting to believe CA crippled the Control bus. Also the CXN (Network streamer from the CX product line) seems to have a smart phone app that can control the volume and mute function of the CXA when connected with the CXN through the control bus. They also mention power control with the [Android app](https://play.google.com/store/apps/details?id=com.audiopartnership.cambridgeconnect), but don't with the [iOS app](https://itunes.apple.com/hr/app/cambridge-connect/id922431442?mt=8).

These are screen caps from the app:
<img width="171" alt="screen shot 2018-03-26 at 18 14 46" src="https://user-images.githubusercontent.com/801034/37918631-f0b6d884-3121-11e8-9c1a-d1c1d8c45a2c.png">

<img width="243" alt="screen shot 2018-03-26 at 18 21 09" src="https://user-images.githubusercontent.com/801034/37918953-d4bcb1ca-3122-11e8-9dcb-6fd2fae564e3.png">

I guess I'm out of luck for complete control unless I'm going to tinker with IR.

**Comment by andrew-bolin** [comment]
You could try running a loop that sends each possible command, 0 to 127 ?
Assuming the Android app can actually control power...

**Comment by andrew-bolin** [comment]
It's been a long time, just thought I'd check in to see if you had any luck?
Very strange that the Android app can apparently control power but not the Apple... probably just some mistake in describing the features. And very strange that they would cripple the control bus, it's more work to do that... More work for less functionality, madness!

**Comment by fritsypeij** [comment]
No, unfortunately I didn’t. IR is the way to go for me. Thanks for getting back :)
